name: s
channels:
    - defaults
dependencies:
    - pip==21.2.2
    - python==3.8.0
    - pip:
        - BeautifulSoup4==4.10.0
        - gdown==4.2.0 
        - nltk==3.6.5
        - huggingface-hub==0.0.19
        - matplotlib==3.5.0
        - numpy==1.21.2
        - scikit-learn
        - openpyxl==3.0.9
        - pandas==1.3.4
        - tokenizers==0.10.3
        - scikit-learn==0.24.2
        - torch==1.10.0
        - torchtext==0.11.0
        - transformers==4.10.2
