name: story-recom
channels:
    - defaults
dependencies:
    - pip=21.2.2
    - python=3.8.0
    - pip:
        - BeautifulSoup4==4.10.0
        - nltk==3.6.5
        - numpy==1.12.2
        - scikit-learn
        - openpyxl==3.0.9
        - pandas==0.17.1
        - tokenizers==0.10.0
        - scikit-learn=0.24.2
